services:
  node-app:
    build: .
    container_name: node-app
    volumes:
      - .:/app
    # Aponta para o diretório da aplicação para que yarn start funcione corretamente
    working_dir: /app/learning-react
    ports:
      - "3000:3000"
    # Mantém o container rodando para criar a aplicação React, usado com working_dir: /app/
    # command: sleep infinity
    command: yarn start
